name: deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-job:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: | 
          python -m pip install twine build
          python -m pip install -e .
      - name: Build package locally
        run: | 
          python -m build
          python -m twine check dist/*
      - name: Upload package to PyPI
        run: | 
          python -m twine upload -r pypi dist/* --verbose