name: deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: | 
          python -m pip install twine build
          python -m pip install -e .
      - name: Build package
        run: | 
          python -m build
          python -m twine check dist/*
      - name: Upload package to TestPyPI
        run: | 
          python -m twine upload -r testpypi dist/* --verbose
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME_TEST }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_TEST }}
      - name: Upload package to PyPI
        run: | 
          python -m twine upload -r pypi dist/* --verbose
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
