name: publish

on:
  workflow_run:
    workflows: ["publish-test"]
    types:
      - completed
    status: success
  workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: | 
          python -m pip install twine build
          python -m pip install -e .

      - name: Build package
        run: | 
          python -m build
          python -m twine check dist/*

      - name: Publish to PyPI 
        uses: pypa/gh-action-pypi-publish@release/v1
