name: test

on: 
  push:
    branches:
      - develop
      - main      

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install package locally
        run: python -m pip install .
      - name: Install python coverage package
        run: python -m pip install coverage
      - name: Run python tests with coverage
        run: python -m coverage run -m unittest
      - name: Produce xml coverage report
        run: python -m coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
