name: test

on: 
  push:
    branches:
      - develop
      - main      

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install package locally
        run: python -m pip install -e .
      - name: Install coverage
        run: python -m pip install coverage
      - name: Run coverage
        run: coverage run --debug=trace --source=src,tests -m unittest discover -s tests
      - name: Print coverage
        run: coverage report -m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
