name: test

on: 
  push:
    branches:
      - develop
      - main      

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install package locally
        run: python -m pip install .
      - name: Run python tests
        run: python -m unittest
