name: Test
on: [push]
jobs:
  Run-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is running on ${{ runner.os }}, triggered by a ${{ github.event_name }} event"
      - run: echo "Running tests for ${{ github.repository }} at branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run python tests
        run: |
          cd ${{ github.workspace }}
          pip install -e .
          python -m unittest
      - run: echo "This job's status is ${{ job.status }}."
