name: test

on: 
  push:
    branches:
      - develop
      - main      

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install package locally
        run: |
          python -m pip install .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run python tests
        run: |
          python -m unittest
      - run: echo "This job's status is ${{ job.status }}."
