name: test

on: 
  push:
    branches:
      - develop
      - main      

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install package locally
        run: python -m pip install .
      - name: Install coverage
        run: python -m pip install coverage
      - name: Run tests
        run: python -m unittest
      - name: Run coverage
        run: python -m coverage xml
      - name: print coverage
        run: cat coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
